# [Info]
site_name: 哈哈就看见的个人网站 # 左上角标题
site_url: https://hahajiukanjian.github.io
site_author: 丁永涛
site_description: 哈哈就看见的个人网站

theme:
  name: material
  palette:
    - scheme: default # 亮色
      primary: indigo # 设置头部框框为紫色
      accent: light blue # 悬停链接、按钮和滚动条
      toggle:
        icon: material/brightness-7
        name: 切换为黑夜模式
    - scheme: slate # 暗色
      primary: black
      toggle:
        icon: material/brightness-4
        name: 切换为白昼模式
  features:
    - navigation.tabs # 启用选项卡
    # - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.instant # 即时加载
    - navigation.instant.prefetch
    - navigation.instant.progress # 加载时间超过400毫秒时，显示进度条
    - navigation.sections # 关闭左侧折叠
    - navigation.path # 打开一个文档时，在文档上方开启导航路径
    - toc.integrate # 将右侧的目录改为在左侧显示
    - search.highlight # 高亮搜索
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - content.code.copy # 可以通过按钮复制代码
    # - header.autohide # 在向下浏览时，自动隐藏标题
    - navigation.footer
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github # 设置了右上角的github图标

edit_uri: edit/main/docs # 编辑按钮跳转的链接
repo_url: https://github.com/hahajiukanjian/hahajiukanjian.github.io # 右上角的仓库链接
repo_name: hahajiukanjian.github.io # 右上角的名字

extra:
  social:
    # - icon: fontawesome/solid/paper-plane
    #   link: hahajiukanjian@outlook.com
    #   name: 电子邮箱 | hahajiukanjian@outlook.com
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/20211181
      name: Bilibili | 哈哈就看见
    - icon: fontawesome/brands/github
      link: https://github.com/hahajiukanjian
      name: GitHub | hahajiukanjian

nav:
  - index.md
  - 技术学习:
    - JavaWeb:
      - Servlet: 技术学习/Java/JavaWeb/Servlet/1-Servlet.md
      - JSP: 技术学习/Java/JavaWeb/Servlet/2-JSP.md
      - EL表达式: 技术学习/Java/JavaWeb/Servlet/3-EL表达式.md
      - JSTL: 技术学习/Java/JavaWeb/Servlet/4-JSTL标签库.md
      - Filter: 技术学习/Java/JavaWeb/Servlet/5-Filter过滤器.md
  - 开发:
    - CPP数据中心:
      - 前期学习:
        - 第7章:
          - 7-11 数据优化: 开发/CPP数据中心/个人笔记/7章/7-11 数据优化.md
        - 第9章:
          - 9-2-Federated存储引擎: 开发/CPP数据中心/个人笔记/9章/9-2-Federated存储引擎.md
          - 9-3-刷新同步: 开发/CPP数据中心/个人笔记/9章/9-3-刷新同步.md
          - 9-4-刷新同步-全表刷新: 开发/CPP数据中心/个人笔记/9章/9-4-刷新同步-全表刷新.md
          - 9-6-基于Federated引擎的增量同步: 开发/CPP数据中心/个人笔记/9章/9-6-基于Federated引擎的增量同步.md
          - FEDERATED引擎: 开发/CPP数据中心/个人笔记/9章/FEDERATED引擎.md
          - tips-刷新同步与增量同步的运行周期: 开发/CPP数据中心/个人笔记/9章/tips-刷新同步与增量同步的运行周期.md
        - 第10章:
          - 10-2-数据清理: 开发/CPP数据中心/个人笔记/10章/10-2-数据清理.md
          - 10-3-数据迁移: 开发/CPP数据中心/个人笔记/10章/10-3-数据迁移.md
          - tips-执行select: 开发/CPP数据中心/个人笔记/10章/tips-执行select.md
        - 第11章:
          - 11-4-Oracle-MySQL的区别: 开发/CPP数据中心/个人笔记/11章/11-4-Oracle-MySQL的区别.md
          - 11-5-Oracle数据库开发基础: 开发/CPP数据中心/个人笔记/11章/11-5-Oracle数据库开发基础.md
          - 11-9-Oracle错误代码判断: 开发/CPP数据中心/个人笔记/11章/11-9-Oracle错误代码判断.md
        - 第12章:
          - 12-2-线程的创建和终止: 开发/CPP数据中心/个人笔记/12章/12-2-线程的创建和终止.md
          - 12-3-线程参数传递: 开发/CPP数据中心/个人笔记/12章/12-3-线程参数传递.md
          - 12-5-线程资源的回收: 开发/CPP数据中心/个人笔记/12章/12-5-线程资源的回收.md
          - 12-6-线程的取消: 开发/CPP数据中心/个人笔记/12章/12-6-线程的取消.md
          - 12-7-线程和信号: 开发/CPP数据中心/个人笔记/12章/12-7-线程和信号.md
          - 12-8-线程安全: 开发/CPP数据中心/个人笔记/12章/12-8-线程安全.md
          - 12-9-线程安全-线程同步: 开发/CPP数据中心/个人笔记/12章/12-9-线程安全-线程同步.md
          - 12-10-线程安全-线程同步-生产消费者模型: 开发/CPP数据中心/个人笔记/12章/12-10-线程安全-线程同步-生产消费者模型.md
          - 12-12-多线程网络服务端: 开发/CPP数据中心/个人笔记/12章/12-12-多线程网络服务端.md
        - 第13章:
          - 13-2-HTTP协议的本质: 开发/CPP数据中心/个人笔记/13章/13-2-HTTP协议的本质.md
          - 13-5-业务需求和表的设计: 开发/CPP数据中心/个人笔记/13章/13-5-业务需求和表的设计.md
          - 13-11-线程池: 开发/CPP数据中心/个人笔记/13章/13-11-线程池.md
        - 第14章:
          - 1 select模型: 开发/CPP数据中心/个人笔记/14、IO复用技术/1 select模型.md
          - 前言: 开发/CPP数据中心/个人笔记/14、IO复用技术/前言.md
      - 复盘:
        - 2、开发永不停机的服务程序:
          - 1 前言: 开发/CPP数据中心/个人笔记/气象中心项目复盘/2、开发永不停机的服务程序/1 前言.md
          - 2 生成测试数据-搭建程序的框架: 开发/CPP数据中心/个人笔记/气象中心项目复盘/2、开发永不停机的服务程序/2 生成测试数据-搭建程序的框架.md
          - 3 生成测试数据-加载站点参数: 开发/CPP数据中心/个人笔记/气象中心项目复盘/2、开发永不停机的服务程序/3 生成测试数据-加载站点参数.md
          - 4 生成测试数据-模拟观测数据: 开发/CPP数据中心/个人笔记/气象中心项目复盘/2、开发永不停机的服务程序/4 生成测试数据-模拟观测数据.md
          - 5 生成测试数据-生成csv文件: 开发/CPP数据中心/个人笔记/气象中心项目复盘/2、开发永不停机的服务程序/5 生成测试数据-生成csv文件.md
          - 6 生成测试数据-生成xml和json文件: 开发/CPP数据中心/个人笔记/气象中心项目复盘/2、开发永不停机的服务程序/6 生成测试数据-生成xml和json文件.md
          - 7 服务程序的调度-Linux信号量: 开发/CPP数据中心/个人笔记/气象中心项目复盘/2、开发永不停机的服务程序/7 服务程序的调度-Linux信号量.md
          - 8 服务程序的调度-Linux多进程: 开发/CPP数据中心/个人笔记/气象中心项目复盘/2、开发永不停机的服务程序/8 服务程序的调度-Linux多进程.md
          - 9 服务程序的调度: 开发/CPP数据中心/个人笔记/气象中心项目复盘/2、开发永不停机的服务程序/9 服务程序的调度.md
          - 10守护进程的实现- Linux共享内存: 开发/CPP数据中心/个人笔记/气象中心项目复盘/2、开发永不停机的服务程序/10守护进程的实现- Linux共享内存.md
          - 11 守护内存的实现-Linux信号量: 开发/CPP数据中心/个人笔记/气象中心项目复盘/2、开发永不停机的服务程序/11 守护内存的实现-Linux信号量.md
          - 12 进程的心跳机制: 开发/CPP数据中心/个人笔记/气象中心项目复盘/2、开发永不停机的服务程序/12 进程的心跳机制.md
        - 4、开发基于tcp协议的文件传输子系统:
          - 1 解决TCP粘包和分包的问题: 开发/CPP数据中心/个人笔记/气象中心项目复盘/4、开发基于tcp协议的文件传输子系统/1 解决TCP粘包和分包的问题.md
          - 2 封装socket的常用函数: 开发/CPP数据中心/个人笔记/气象中心项目复盘/4、开发基于tcp协议的文件传输子系统/2 封装socket的常用函数.md
        - 5、搞定MySQL数据库的开发:
          - 1 创建信息表: 开发/CPP数据中心/个人笔记/气象中心项目复盘/5、搞定MySQL数据库的开发/1 创建信息表.md
          - 2 插入数据: 开发/CPP数据中心/个人笔记/气象中心项目复盘/5、搞定MySQL数据库的开发/2 插入数据.md
          - 3 修改数据: 开发/CPP数据中心/个人笔记/气象中心项目复盘/5、搞定MySQL数据库的开发/3 修改数据.md
          - 4 查找信息表数据: 开发/CPP数据中心/个人笔记/气象中心项目复盘/5、搞定MySQL数据库的开发/4 查找信息表数据.md
          - 5 删除信息表数据: 开发/CPP数据中心/个人笔记/气象中心项目复盘/5、搞定MySQL数据库的开发/5 删除信息表数据.md
          - 6 二进制大对象的存取: 开发/CPP数据中心/个人笔记/气象中心项目复盘/5、搞定MySQL数据库的开发/6 二进制大对象的存取.md
          - 7 数据库开发注意事项和技巧(重要): 开发/CPP数据中心/个人笔记/气象中心项目复盘/5、搞定MySQL数据库的开发/7 数据库开发注意事项和技巧(重要).md
          - 8 站点参数文件入库: 开发/CPP数据中心/个人笔记/气象中心项目复盘/5、搞定MySQL数据库的开发/8 站点参数文件入库.md
          - 9 站点数据文件入库: 开发/CPP数据中心/个人笔记/气象中心项目复盘/5、搞定MySQL数据库的开发/9 站点数据文件入库.md
          - 10-1 优化数据入库程序: 开发/CPP数据中心/个人笔记/气象中心项目复盘/5、搞定MySQL数据库的开发/10-1 优化数据入库程序.md
          - 10-2 优化数据入库程序: 开发/CPP数据中心/个人笔记/气象中心项目复盘/5、搞定MySQL数据库的开发/10-2 优化数据入库程序.md
          - 11 执行SQL脚本文件: 开发/CPP数据中心/个人笔记/气象中心项目复盘/5、搞定MySQL数据库的开发/11 执行SQL脚本文件.md
          - 12 总结: 开发/CPP数据中心/个人笔记/气象中心项目复盘/5、搞定MySQL数据库的开发/12 总结.md
        - 6、数据抽取子系统复盘:
          - 前言: 开发/CPP数据中心/个人笔记/气象中心项目复盘/6、数据抽取子系统复盘/前言.md
          - 1 搭建框架、解析参数: 开发/CPP数据中心/个人笔记/气象中心项目复盘/6、数据抽取子系统复盘/1 搭建框架、解析参数.md
          - 2 全量抽取数据，生成xml: 开发/CPP数据中心/个人笔记/气象中心项目复盘/6、数据抽取子系统复盘/2 全量抽取数据，生成xml.md
          - 3 全量抽取数据，写入xml: 开发/CPP数据中心/个人笔记/气象中心项目复盘/6、数据抽取子系统复盘/3 全量抽取数据，写入xml.md
          - 4 增量抽取数据: 开发/CPP数据中心/个人笔记/气象中心项目复盘/6、数据抽取子系统复盘/4 增量抽取数据.md
          - 总结: 开发/CPP数据中心/个人笔记/气象中心项目复盘/6、数据抽取子系统复盘/总结.md
        - 7、开发数据入库子系统:
          - 前言: 开发/CPP数据中心/个人笔记/气象中心项目复盘/7、开发数据入库子系统/前言.md
          - 数据入库1-解析入库参数: 开发/CPP数据中心/个人笔记/气象中心项目复盘/7、开发数据入库子系统/数据入库1-解析入库参数.md
          - 数据入库2-查找数据字典: 开发/CPP数据中心/个人笔记/气象中心项目复盘/7、开发数据入库子系统/数据入库2-查找数据字典.md
          - 数据入库3-拼接SQL语句: 开发/CPP数据中心/个人笔记/气象中心项目复盘/7、开发数据入库子系统/数据入库3-拼接SQL语句.md
          - 数据入库4-绑定SQL语句的参数: 开发/CPP数据中心/个人笔记/气象中心项目复盘/7、开发数据入库子系统/数据入库4-绑定SQL语句的参数.md
          - 数据入库5-执行插入和更新: 开发/CPP数据中心/个人笔记/气象中心项目复盘/7、开发数据入库子系统/数据入库5-执行插入和更新.md
          - 数据入库6-完善和优化: 开发/CPP数据中心/个人笔记/气象中心项目复盘/7、开发数据入库子系统/数据入库6-完善和优化.md
        - 9、开发数据同步子系统:
          - 前言: 开发/CPP数据中心/个人笔记/气象中心项目复盘/9、开发数据同步子系统/前言.md
          - 1 Federated存储引擎: 开发/CPP数据中心/个人笔记/气象中心项目复盘/9、开发数据同步子系统/1 Federated存储引擎.md
          - 2 刷新同步-搭建程序的框架: 开发/CPP数据中心/个人笔记/气象中心项目复盘/9、开发数据同步子系统/2 刷新同步-搭建程序的框架.md
          - 3 刷新同步-全表刷新: 开发/CPP数据中心/个人笔记/气象中心项目复盘/9、开发数据同步子系统/3 刷新同步-全表刷新.md
          - 4 刷新同步-分批刷新: 开发/CPP数据中心/个人笔记/气象中心项目复盘/9、开发数据同步子系统/4 刷新同步-分批刷新.md
          - 5 增量同步-基于Federated引擎: 开发/CPP数据中心/个人笔记/气象中心项目复盘/9、开发数据同步子系统/5 增量同步-基于Federated引擎.md
          - 6 增量同步-不采用Federated引擎: 开发/CPP数据中心/个人笔记/气象中心项目复盘/9、开发数据同步子系统/6 增量同步-不采用Federated引擎.md
        - 10、开发数据管理子系统:
          - 数据清理: 开发/CPP数据中心/个人笔记/气象中心项目复盘/10、开发数据管理子系统/数据清理.md
        - 12、Linux线程:
          - 前言: 开发/CPP数据中心/个人笔记/气象中心项目复盘/12、Linux线程/前言.md
          - 1 线程的创建与终止: 开发/CPP数据中心/个人笔记/气象中心项目复盘/12、Linux线程/1 线程的创建与终止.md
          - 2 线程参数的传递: 开发/CPP数据中心/个人笔记/气象中心项目复盘/12、Linux线程/2 线程参数的传递.md
          - 3 线程资源的回收: 开发/CPP数据中心/个人笔记/气象中心项目复盘/12、Linux线程/3 线程资源的回收.md
          - 4 线程的取消: 开发/CPP数据中心/个人笔记/气象中心项目复盘/12、Linux线程/4 线程的取消.md
          - 5 线程和信号: 开发/CPP数据中心/个人笔记/气象中心项目复盘/12、Linux线程/5 线程和信号.md
          - 6 线程安全: 开发/CPP数据中心/个人笔记/气象中心项目复盘/12、Linux线程/6 线程安全.md
          - 7 线程同步: 开发/CPP数据中心/个人笔记/气象中心项目复盘/12、Linux线程/7 线程同步.md
          - 8 生产消费者模型的实现-前言: 开发/CPP数据中心/个人笔记/气象中心项目复盘/12、Linux线程/8 生产消费者模型的实现-前言.md
          - 9 生产消费者模型的实现-互斥锁+条件变量: 开发/CPP数据中心/个人笔记/气象中心项目复盘/12、Linux线程/9 生产消费者模型的实现-互斥锁+条件变量.md
          - 10 生产消费者模型的实现-信号量: 开发/CPP数据中心/个人笔记/气象中心项目复盘/12、Linux线程/10 生产消费者模型的实现-信号量.md
          - 11 开发多线程的网络服务端: 开发/CPP数据中心/个人笔记/气象中心项目复盘/12、Linux线程/11 开发多线程的网络服务端.md
        - 13、开发数据服务总线:
          - 前言: 开发/CPP数据中心/个人笔记/气象中心项目复盘/13、开发数据服务总线/前言.md
          - 1 HTTP协议的本质: 开发/CPP数据中心/个人笔记/气象中心项目复盘/13、开发数据服务总线/1 HTTP协议的本质.md
          - 2 HTTP数据访问接口的实现: 开发/CPP数据中心/个人笔记/气象中心项目复盘/13、开发数据服务总线/2 HTTP数据访问接口的实现.md
          - 3 业务需求和表的设计: 开发/CPP数据中心/个人笔记/气象中心项目复盘/13、开发数据服务总线/3 业务需求和表的设计.md
          - 4 功能的初步实现: 开发/CPP数据中心/个人笔记/气象中心项目复盘/13、开发数据服务总线/4 功能的初步实现.md
          - 5 数据库连接池的实现: 开发/CPP数据中心/个人笔记/气象中心项目复盘/13、开发数据服务总线/5 数据库连接池的实现.md
          - 6 数据库连接池的优化: 开发/CPP数据中心/个人笔记/气象中心项目复盘/13、开发数据服务总线/6 数据库连接池的优化.md
          - 7 线程池的实现: 开发/CPP数据中心/个人笔记/气象中心项目复盘/13、开发数据服务总线/7 线程池的实现.md


markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.highlight: # 代码块高亮
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等

copyright: 哈哈就看见