# [Info]
site_name: 哈哈就看见的个人网站 # 左上角标题
site_url: https://hahajiukanjian.github.io
site_author: 丁永涛
site_description: 哈哈就看见的个人网站

theme:
  name: material
  palette:
    - scheme: default # 亮色
      primary: indigo # 设置头部框框为紫色
      accent: light blue # 悬停链接、按钮和滚动条
      toggle:
        icon: material/brightness-7
        name: 切换为黑夜模式
    - scheme: slate # 暗色
      primary: black
      toggle:
        icon: material/brightness-4
        name: 切换为白昼模式
  features:
    - navigation.tabs # 启用选项卡
    # - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.instant # 即时加载
    - navigation.instant.prefetch
    - navigation.instant.progress # 加载时间超过400毫秒时，显示进度条
    - navigation.sections # 关闭左侧折叠
    - navigation.path # 打开一个文档时，在文档上方开启导航路径
    - toc.integrate # 将右侧的目录改为在左侧显示
    - search.highlight # 高亮搜索
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - content.code.copy # 可以通过按钮复制代码
    # - header.autohide # 在向下浏览时，自动隐藏标题
    - navigation.footer
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github # 设置了右上角的github图标

edit_uri: edit/main/docs # 编辑按钮跳转的链接
repo_url: https://github.com/hahajiukanjian/hahajiukanjian.github.io # 右上角的仓库链接
repo_name: hahajiukanjian.github.io # 右上角的名字

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: hahajiukanjian@outlook.com
      name: 电子邮箱 | hahajiukanjian@outlook.com
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/20211181
      name: Bilibili | 哈哈就看见
    - icon: fontawesome/brands/github
      link: https://github.com/hahajiukanjian
      name: GitHub | hahajiukanjian

nav:
  - index.md
  - 技术学习:
    - JavaWeb:
      - Servlet-JSP: 技术学习/Java/JavaWeb/Servlet/Servlet-JSP.md
      - Servlet课程讲义: 技术学习/Java/JavaWeb/Servlet/Servlet-JSP-课堂笔记.md
  - 开发:
      - CPP数据中心


plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  # - git-authors # 显示文章作者

markdown_extensions:
  - toc:
      toc_depth: 2
  - pymdownx.highlight: # 代码块高亮
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等

copyright: 哈哈就看见