# [Info]
site_name: 哈哈就看见的个人网站 # 左上角标题
site_url: https://hahajiukanjian.github.io
site_author: 丁永涛
site_description: 哈哈就看见的个人网站

theme:
  name: material
  palette:
    # 白昼
    - media: "(prefers-color-scheme: light)"
      scheme: default # 亮色
      primary: light blue # 设置头部框框为蓝色
      accent: light blue # 悬停链接、按钮和滚动条
      toggle:
        icon: material/brightness-7
        name: 切换为黑夜模式
    # 黑夜
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 暗色
      toggle:
        icon: material/brightness-4
        name: 切换为白昼模式
  features:
    - navigation.instant

nav:
  - index.md
  - 技术学习:
    - JavaWeb:
      - Servlet-JSP: 技术学习/Java/JavaWeb/Servlet/Servlet-JSP.md
      - Servlet课程讲义: 技术学习/Java/JavaWeb/Servlet/Servlet-JSP-课堂笔记.md
  - 开发:
      - CPP数据中心
